# Reflexec features

Feature: Command execution output is generated by output plugins

  Scenario: Execute command with default output plugin
    When Reflexec is executed with options: --max-execs=1 -- date
    Then Command finishes with return code 0
    And Command output contains the following strings:
    """
    Starting reflexec instance: date
    Executing command (round #1): date
    Command finished successfully
    Duration of round #1:
    """


  @autodoc
  Scenario: Execute command with JSON output plugin
    When Reflexec is executed with options: --max-execs=1 --output=json uname
    Then Command finishes with return code 0
    And Output contains the following JSON value:
    """
    {
      "event": "init",
      "msg": "Starting reflexec instance",
      "name": "uname"
    }
    """
    And Output contains the following JSON value:
    """
    {
      "event": "start_exec",
      "msg": "Executing command",
      "command": ["uname"],
      "exec_count": 1
    }
    """
    And Output contains the following JSON value:
    """
    {
      "event": "finish_exec",
      "msg": "Command finished successfully",
      "duration": {"days": 0, "hours": 0, "minutes": 0, "seconds": 0.001},
      "duration_str": "0.001 sec",
      "exec_count": 1
    }
    """


  @autodoc
  Scenario: Execute command with output plugin described with reference
    When Reflexec is executed with options: --max-execs=1 -o reflexec.output.plugin:LoggerOutputPlugin true
    Then Command finishes with return code 0
    And Command output contains the following strings:
    """
    INFO: Starting reflexec instance: true
    INFO: Executing command (round #1): true
    INFO: Command finished successfully
    INFO: Duration of round #1:
    """


  Scenario: Execute command with invalid output plugin
    When Reflexec is executed with options: --max-execs=1 --output=INVALID -- date
    Then Command finishes with return code 0
    And Command output contains the following strings:
    """
    Invalid output plugin "INVALID"
    No output plugins specified, using default
    Starting reflexec instance: date
    Executing command (round #1): date
    Command finished successfully
    Duration of round #1:
    """


  Scenario Outline: Execute command with multiple output plugins
    # define output plugins in separate args
    When Reflexec is executed with options: --max-execs=1 <output_plugin> date
    Then Command finishes with return code 0
    And Command output contains the following strings:
    """
    Executing command (round #1): date
    """
    And Output contains the following JSON value:
    """
    {
      "event": "start_exec",
      "msg": "Executing command",
      "command": ["date"],
      "exec_count": 1
    }
    """

    Examples:
      | output_plugin                  |
      | --output=json --output=default |
      | --output=json,default          |


  Scenario: Execute command with all internal output plugins

    Utilize all output messages of all output plugins

    Given File script.sh is:
    """
    #!/bin/sh

    set -e

    # touch file "stamp" to notify test
    touch stamp

    # use file "counter" to count executions
    ROUND=1
    if [ -f counter ]; then
      ROUND="$(cat counter)"
    fi
    echo "$(expr ${ROUND} + 1)" > counter

    # return error on second execution
    test "${ROUND}" != 2

    exit 0
    """
    And Reflexec config file is:
    """
    [reflexec]
    watch = stamp
    max_execs = 3
    delay = 0.1

    # use all builtin plugins for output
    output = default, json, log, clear, colorterm, titlebar, fancytitlebar

    # execute command using shell command interpreter:
    command = sh script.sh
    """
    And File "stamp" does not exist
    And File "counter" does not exist

    # ROUND 1 - start Reflexec with command execution
    When Reflexec is executed in background
    Then File "stamp" is created within 3 seconds

    # ROUND 2 - change watched file
    When Wait for 1 second
    And File "stamp" is removed
    # Reflexec must detect file change and create file again
    Then File "stamp" is created within 3 seconds

    # ROUND 3 - force command execution using QUIT signal
    When Wait for 1 second
    And QUIT signal is sent to Reflexec
    # Reflexec must create file again
    Then File "stamp" is created within 3 seconds
    And Command finishes with return code 0
